name: Build Android APK

on:
  push:
    branches:
      - main # Mude para 'master' se a sua branch principal tiver esse nome

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências (Capacitor)
        run: npm install

      - name: Adicionar plataforma Android
        run: npx cap add android

      - name: Sincronizar arquivos web para o Android
        run: npx cap sync android

      - name: Configurar Java JDK 17 (Requisito do Android)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compilar o APK
        working-directory: ./android
        run: ./gradlew assembleDebug

      - name: Disponibilizar o APK para download
        uses: actions/upload-artifact@v4
        with:
          name: meu-aplicativo-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk